import { ISelectOption } from 'components/common/inputs/inputTypes';

export enum Language {
  Other = 0,
  Polish = 1,
  African = 2,
  Arabic = 3,
  Bengali = 4,
  Bulgarian = 5,
  Catalan = 6,
  Croatian = 7,
  Czech = 8,
  Danish = 9,
  Dutch = 10,
  English = 11,
  Estonian = 12,
  Finnish = 13,
  French = 14,
  German = 15,
  Greek = 16,
  Haitian = 17,
  Hebrew = 18,
  Hindi = 19,
  Hungarian = 20,
  Icelandic = 21,
  Indonesian = 22,
  Irish = 23,
  Italian = 24,
  Japanese = 25,
  Kazakh = 26,
  Korean = 27,
  Lao = 28,
  Latin = 29,
  Lithuanian = 30,
  Latvian = 31,
  Malay = 32,
  Norwegian = 33,
  Panjabi = 34,
  Persian = 35,
  Portuguese = 36,
  Romanian = 37,
  Russian = 38,
  Sanskrit = 39,
  Slovak = 40,
  Slovenian = 41,
  Spanish = 42,
  Swedish = 43,
  Tagalog = 44,
  Telugu = 45,
  Thai = 46,
  Turkish = 47,
  Ukrainian = 48,
  Urdu = 49,
  Vietnamese = 50,
  Zulu = 51,
}

export const LanguageLabels = {
  [Language.Other]: 'Inny',
  [Language.Polish]: 'Polski',
  [Language.African]: 'Afrykański',
  [Language.Arabic]: 'Arabski',
  [Language.Bengali]: 'Bengalski',
  [Language.Bulgarian]: 'Bułgarski',
  [Language.Catalan]: 'Kataloński',
  [Language.Croatian]: 'Chorwacki',
  [Language.Czech]: 'Czeski',
  [Language.Danish]: 'Duński',
  [Language.Dutch]: 'Holenderski',
  [Language.English]: 'Angielski',
  [Language.Estonian]: 'Estoński',
  [Language.Finnish]: 'Fiński',
  [Language.French]: 'Francuski',
  [Language.German]: 'Niemiecki',
  [Language.Greek]: 'Grecki',
  [Language.Haitian]: 'Haitański',
  [Language.Hebrew]: 'Hebrajski',
  [Language.Hindi]: 'Hindi',
  [Language.Hungarian]: 'Węgierski',
  [Language.Icelandic]: 'Islandzki',
  [Language.Indonesian]: 'Indonezyjski',
  [Language.Irish]: 'Irlandzki',
  [Language.Italian]: 'Włoski',
  [Language.Japanese]: 'Japoński',
  [Language.Kazakh]: 'Kazachski',
  [Language.Korean]: 'Koreański',
  [Language.Lao]: 'Laotański',
  [Language.Latin]: 'Łaciński',
  [Language.Lithuanian]: 'Litewski',
  [Language.Latvian]: 'Łotewski',
  [Language.Malay]: 'Malajski',
  [Language.Norwegian]: 'Norweski',
  [Language.Panjabi]: 'Panjabi',
  [Language.Persian]: 'Perski',
  [Language.Portuguese]: 'Portugalski',
  [Language.Romanian]: 'Rumuński',
  [Language.Russian]: 'Rosyjski',
  [Language.Sanskrit]: 'Sanskryt',
  [Language.Slovak]: 'Słowacki',
  [Language.Slovenian]: 'Słoweński',
  [Language.Spanish]: 'Hiszpański',
  [Language.Swedish]: 'Szwedzki',
  [Language.Tagalog]: 'Tagalski',
  [Language.Telugu]: 'Telugu',
  [Language.Thai]: 'Tajski',
  [Language.Turkish]: 'Turecki',
  [Language.Ukrainian]: 'Ukraiński',
  [Language.Urdu]: 'Urdu',
  [Language.Vietnamese]: 'Wietnamski',
  [Language.Zulu]: 'Zulu',
};

export const getLanguageOptions = (): Array<ISelectOption> =>
  Object.entries(LanguageLabels).map(([key, label]) => ({
    label,
    value: key,
  }));
