apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: justwin-cmsfrontend-hpa
  namespace: development
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: justwin-cmsfrontend-deployment
  targetCPUUtilizationPercentage: 70